export const countryNameMap: Record<string, string> = {
  'US': 'Vereinigte Staaten',
  'DE': 'Deutschland',
  'GB': 'Großbritannien',
  'UK': 'Großbritannien',
  'FR': 'Frankreich',
  'IT': 'Italien',
  'ES': 'Spanien',
  'NL': 'Niederlande',
  'BE': 'Belgien',
  'AT': 'Österreich',
  'CH': 'Schweiz',
  'SE': 'Schweden',
  'NO': 'Norwegen',
  'DK': 'Dänemark',
  'FI': 'Finnland',
  'PL': 'Polen',
  'CZ': 'Tschechien',
  'HU': 'Ungarn',
  'RO': 'Rumänien',
  'GR': 'Griechenland',
  'PT': 'Portugal',
  'IE': 'Irland',
  'LU': 'Luxemburg',
  'CN': 'China',
  'JP': 'Japan',
  'KR': 'Südkorea',
  'IN': 'Indien',
  'AU': 'Australien',
  'CA': 'Kanada',
  'MX': 'Mexiko',
  'BR': 'Brasilien',
  'AR': 'Argentinien',
  'CL': 'Chile',
  'ZA': 'Südafrika',
  'RU': 'Russland',
  'TR': 'Türkei',
  'SA': 'Saudi-Arabien',
  'AE': 'Vereinigte Arabische Emirate',
  'IL': 'Israel',
  'SG': 'Singapur',
  'TH': 'Thailand',
  'MY': 'Malaysia',
  'ID': 'Indonesien',
  'PH': 'Philippinen',
  'VN': 'Vietnam',
  'NZ': 'Neuseeland',
};

export const getCountryName = (countryCode: string | undefined): string => {
  if (!countryCode) return '';
  return countryNameMap[countryCode.toUpperCase()] || countryCode;
};
