-- Add multi-currency columns to financial_statements table
-- Original values (_orig), USD, GBP, JPY, AUD, CNY, MXN, DKK conversions

-- Core financial metrics
ALTER TABLE financial_statements 
  ADD COLUMN IF NOT EXISTS revenue_orig numeric,
  ADD COLUMN IF NOT EXISTS revenue_usd numeric,
  ADD COLUMN IF NOT EXISTS revenue_gbp numeric,
  ADD COLUMN IF NOT EXISTS revenue_jpy numeric,
  ADD COLUMN IF NOT EXISTS revenue_aud numeric,
  ADD COLUMN IF NOT EXISTS revenue_cny numeric,
  ADD COLUMN IF NOT EXISTS revenue_mxn numeric,
  ADD COLUMN IF NOT EXISTS revenue_dkk numeric,
  
  ADD COLUMN IF NOT EXISTS ebitda_orig numeric,
  ADD COLUMN IF NOT EXISTS ebitda_usd numeric,
  ADD COLUMN IF NOT EXISTS ebitda_gbp numeric,
  ADD COLUMN IF NOT EXISTS ebitda_jpy numeric,
  ADD COLUMN IF NOT EXISTS ebitda_aud numeric,
  ADD COLUMN IF NOT EXISTS ebitda_cny numeric,
  ADD COLUMN IF NOT EXISTS ebitda_mxn numeric,
  ADD COLUMN IF NOT EXISTS ebitda_dkk numeric,
  
  ADD COLUMN IF NOT EXISTS ebit_orig numeric,
  ADD COLUMN IF NOT EXISTS ebit_usd numeric,
  ADD COLUMN IF NOT EXISTS ebit_gbp numeric,
  ADD COLUMN IF NOT EXISTS ebit_jpy numeric,
  ADD COLUMN IF NOT EXISTS ebit_aud numeric,
  ADD COLUMN IF NOT EXISTS ebit_cny numeric,
  ADD COLUMN IF NOT EXISTS ebit_mxn numeric,
  ADD COLUMN IF NOT EXISTS ebit_dkk numeric,
  
  ADD COLUMN IF NOT EXISTS net_income_orig numeric,
  ADD COLUMN IF NOT EXISTS net_income_usd numeric,
  ADD COLUMN IF NOT EXISTS net_income_gbp numeric,
  ADD COLUMN IF NOT EXISTS net_income_jpy numeric,
  ADD COLUMN IF NOT EXISTS net_income_aud numeric,
  ADD COLUMN IF NOT EXISTS net_income_cny numeric,
  ADD COLUMN IF NOT EXISTS net_income_mxn numeric,
  ADD COLUMN IF NOT EXISTS net_income_dkk numeric,
  
  ADD COLUMN IF NOT EXISTS total_assets_orig numeric,
  ADD COLUMN IF NOT EXISTS total_assets_usd numeric,
  ADD COLUMN IF NOT EXISTS total_assets_gbp numeric,
  ADD COLUMN IF NOT EXISTS total_assets_jpy numeric,
  ADD COLUMN IF NOT EXISTS total_assets_aud numeric,
  ADD COLUMN IF NOT EXISTS total_assets_cny numeric,
  ADD COLUMN IF NOT EXISTS total_assets_mxn numeric,
  ADD COLUMN IF NOT EXISTS total_assets_dkk numeric,
  
  ADD COLUMN IF NOT EXISTS total_current_assets_orig numeric,
  ADD COLUMN IF NOT EXISTS total_current_assets_usd numeric,
  ADD COLUMN IF NOT EXISTS total_current_assets_gbp numeric,
  ADD COLUMN IF NOT EXISTS total_current_assets_jpy numeric,
  ADD COLUMN IF NOT EXISTS total_current_assets_aud numeric,
  ADD COLUMN IF NOT EXISTS total_current_assets_cny numeric,
  ADD COLUMN IF NOT EXISTS total_current_assets_mxn numeric,
  ADD COLUMN IF NOT EXISTS total_current_assets_dkk numeric,
  
  ADD COLUMN IF NOT EXISTS total_current_liabilities_orig numeric,
  ADD COLUMN IF NOT EXISTS total_current_liabilities_usd numeric,
  ADD COLUMN IF NOT EXISTS total_current_liabilities_gbp numeric,
  ADD COLUMN IF NOT EXISTS total_current_liabilities_jpy numeric,
  ADD COLUMN IF NOT EXISTS total_current_liabilities_aud numeric,
  ADD COLUMN IF NOT EXISTS total_current_liabilities_cny numeric,
  ADD COLUMN IF NOT EXISTS total_current_liabilities_mxn numeric,
  ADD COLUMN IF NOT EXISTS total_current_liabilities_dkk numeric,
  
  ADD COLUMN IF NOT EXISTS total_debt_orig numeric,
  ADD COLUMN IF NOT EXISTS total_debt_usd numeric,
  ADD COLUMN IF NOT EXISTS total_debt_gbp numeric,
  ADD COLUMN IF NOT EXISTS total_debt_jpy numeric,
  ADD COLUMN IF NOT EXISTS total_debt_aud numeric,
  ADD COLUMN IF NOT EXISTS total_debt_cny numeric,
  ADD COLUMN IF NOT EXISTS total_debt_mxn numeric,
  ADD COLUMN IF NOT EXISTS total_debt_dkk numeric,
  
  ADD COLUMN IF NOT EXISTS total_stockholders_equity_orig numeric,
  ADD COLUMN IF NOT EXISTS total_stockholders_equity_usd numeric,
  ADD COLUMN IF NOT EXISTS total_stockholders_equity_gbp numeric,
  ADD COLUMN IF NOT EXISTS total_stockholders_equity_jpy numeric,
  ADD COLUMN IF NOT EXISTS total_stockholders_equity_aud numeric,
  ADD COLUMN IF NOT EXISTS total_stockholders_equity_cny numeric,
  ADD COLUMN IF NOT EXISTS total_stockholders_equity_mxn numeric,
  ADD COLUMN IF NOT EXISTS total_stockholders_equity_dkk numeric,
  
  ADD COLUMN IF NOT EXISTS cash_and_equivalents_orig numeric,
  ADD COLUMN IF NOT EXISTS cash_and_equivalents_usd numeric,
  ADD COLUMN IF NOT EXISTS cash_and_equivalents_gbp numeric,
  ADD COLUMN IF NOT EXISTS cash_and_equivalents_jpy numeric,
  ADD COLUMN IF NOT EXISTS cash_and_equivalents_aud numeric,
  ADD COLUMN IF NOT EXISTS cash_and_equivalents_cny numeric,
  ADD COLUMN IF NOT EXISTS cash_and_equivalents_mxn numeric,
  ADD COLUMN IF NOT EXISTS cash_and_equivalents_dkk numeric,
  
  ADD COLUMN IF NOT EXISTS interest_expense_orig numeric,
  ADD COLUMN IF NOT EXISTS interest_expense_usd numeric,
  ADD COLUMN IF NOT EXISTS interest_expense_gbp numeric,
  ADD COLUMN IF NOT EXISTS interest_expense_jpy numeric,
  ADD COLUMN IF NOT EXISTS interest_expense_aud numeric,
  ADD COLUMN IF NOT EXISTS interest_expense_cny numeric,
  ADD COLUMN IF NOT EXISTS interest_expense_mxn numeric,
  ADD COLUMN IF NOT EXISTS interest_expense_dkk numeric,
  
  ADD COLUMN IF NOT EXISTS operating_cash_flow_orig numeric,
  ADD COLUMN IF NOT EXISTS operating_cash_flow_usd numeric,
  ADD COLUMN IF NOT EXISTS operating_cash_flow_gbp numeric,
  ADD COLUMN IF NOT EXISTS operating_cash_flow_jpy numeric,
  ADD COLUMN IF NOT EXISTS operating_cash_flow_aud numeric,
  ADD COLUMN IF NOT EXISTS operating_cash_flow_cny numeric,
  ADD COLUMN IF NOT EXISTS operating_cash_flow_mxn numeric,
  ADD COLUMN IF NOT EXISTS operating_cash_flow_dkk numeric,
  
  ADD COLUMN IF NOT EXISTS capital_expenditure_orig numeric,
  ADD COLUMN IF NOT EXISTS capital_expenditure_usd numeric,
  ADD COLUMN IF NOT EXISTS capital_expenditure_gbp numeric,
  ADD COLUMN IF NOT EXISTS capital_expenditure_jpy numeric,
  ADD COLUMN IF NOT EXISTS capital_expenditure_aud numeric,
  ADD COLUMN IF NOT EXISTS capital_expenditure_cny numeric,
  ADD COLUMN IF NOT EXISTS capital_expenditure_mxn numeric,
  ADD COLUMN IF NOT EXISTS capital_expenditure_dkk numeric,
  
  ADD COLUMN IF NOT EXISTS free_cash_flow_orig numeric,
  ADD COLUMN IF NOT EXISTS free_cash_flow_usd numeric,
  ADD COLUMN IF NOT EXISTS free_cash_flow_gbp numeric,
  ADD COLUMN IF NOT EXISTS free_cash_flow_jpy numeric,
  ADD COLUMN IF NOT EXISTS free_cash_flow_aud numeric,
  ADD COLUMN IF NOT EXISTS free_cash_flow_cny numeric,
  ADD COLUMN IF NOT EXISTS free_cash_flow_mxn numeric,
  ADD COLUMN IF NOT EXISTS free_cash_flow_dkk numeric,
  
  ADD COLUMN IF NOT EXISTS dividends_paid_orig numeric,
  ADD COLUMN IF NOT EXISTS dividends_paid_usd numeric,
  ADD COLUMN IF NOT EXISTS dividends_paid_gbp numeric,
  ADD COLUMN IF NOT EXISTS dividends_paid_jpy numeric,
  ADD COLUMN IF NOT EXISTS dividends_paid_aud numeric,
  ADD COLUMN IF NOT EXISTS dividends_paid_cny numeric,
  ADD COLUMN IF NOT EXISTS dividends_paid_mxn numeric,
  ADD COLUMN IF NOT EXISTS dividends_paid_dkk numeric,
  
  ADD COLUMN IF NOT EXISTS other_adjustments_net_income_orig numeric,
  ADD COLUMN IF NOT EXISTS other_adjustments_net_income_usd numeric,
  ADD COLUMN IF NOT EXISTS other_adjustments_net_income_gbp numeric,
  ADD COLUMN IF NOT EXISTS other_adjustments_net_income_jpy numeric,
  ADD COLUMN IF NOT EXISTS other_adjustments_net_income_aud numeric,
  ADD COLUMN IF NOT EXISTS other_adjustments_net_income_cny numeric,
  ADD COLUMN IF NOT EXISTS other_adjustments_net_income_mxn numeric,
  ADD COLUMN IF NOT EXISTS other_adjustments_net_income_dkk numeric,
  
  ADD COLUMN IF NOT EXISTS income_tax_expense_orig numeric,
  ADD COLUMN IF NOT EXISTS income_tax_expense_usd numeric,
  ADD COLUMN IF NOT EXISTS income_tax_expense_gbp numeric,
  ADD COLUMN IF NOT EXISTS income_tax_expense_jpy numeric,
  ADD COLUMN IF NOT EXISTS income_tax_expense_aud numeric,
  ADD COLUMN IF NOT EXISTS income_tax_expense_cny numeric,
  ADD COLUMN IF NOT EXISTS income_tax_expense_mxn numeric,
  ADD COLUMN IF NOT EXISTS income_tax_expense_dkk numeric,
  
  ADD COLUMN IF NOT EXISTS income_before_tax_orig numeric,
  ADD COLUMN IF NOT EXISTS income_before_tax_usd numeric,
  ADD COLUMN IF NOT EXISTS income_before_tax_gbp numeric,
  ADD COLUMN IF NOT EXISTS income_before_tax_jpy numeric,
  ADD COLUMN IF NOT EXISTS income_before_tax_aud numeric,
  ADD COLUMN IF NOT EXISTS income_before_tax_cny numeric,
  ADD COLUMN IF NOT EXISTS income_before_tax_mxn numeric,
  ADD COLUMN IF NOT EXISTS income_before_tax_dkk numeric,
  
  ADD COLUMN IF NOT EXISTS eps_diluted_orig numeric,
  ADD COLUMN IF NOT EXISTS eps_diluted_usd numeric,
  ADD COLUMN IF NOT EXISTS eps_diluted_gbp numeric,
  ADD COLUMN IF NOT EXISTS eps_diluted_jpy numeric,
  ADD COLUMN IF NOT EXISTS eps_diluted_aud numeric,
  ADD COLUMN IF NOT EXISTS eps_diluted_cny numeric,
  ADD COLUMN IF NOT EXISTS eps_diluted_mxn numeric,
  ADD COLUMN IF NOT EXISTS eps_diluted_dkk numeric;