-- Add missing Key Metrics and Financial Ratios columns to financial_statements table

-- Key Metrics columns (from FMP Key Metrics API)
ALTER TABLE financial_statements
ADD COLUMN IF NOT EXISTS graham_number_orig numeric,
ADD COLUMN IF NOT EXISTS graham_number_usd numeric,
ADD COLUMN IF NOT EXISTS graham_number_eur numeric,
ADD COLUMN IF NOT EXISTS pe_ratio numeric,
ADD COLUMN IF NOT EXISTS pb_ratio numeric,
ADD COLUMN IF NOT EXISTS ps_ratio numeric,
ADD COLUMN IF NOT EXISTS pfcf_ratio numeric,
ADD COLUMN IF NOT EXISTS peg_ratio numeric,
ADD COLUMN IF NOT EXISTS ev_to_ebitda numeric,
ADD COLUMN IF NOT EXISTS ev_to_sales numeric,
ADD COLUMN IF NOT EXISTS ev_to_operating_cash_flow numeric,
ADD COLUMN IF NOT EXISTS enterprise_value_orig numeric,
ADD COLUMN IF NOT EXISTS enterprise_value_usd numeric,
ADD COLUMN IF NOT EXISTS enterprise_value_eur numeric,
ADD COLUMN IF NOT EXISTS roic numeric,
ADD COLUMN IF NOT EXISTS roce numeric,
ADD COLUMN IF NOT EXISTS roa numeric,
ADD COLUMN IF NOT EXISTS roe numeric,
ADD COLUMN IF NOT EXISTS net_debt_to_ebitda numeric,
ADD COLUMN IF NOT EXISTS dividend_yield numeric,
ADD COLUMN IF NOT EXISTS book_value_per_share numeric,
ADD COLUMN IF NOT EXISTS tangible_book_value_per_share numeric,
ADD COLUMN IF NOT EXISTS working_capital_orig numeric,
ADD COLUMN IF NOT EXISTS working_capital_usd numeric,
ADD COLUMN IF NOT EXISTS working_capital_eur numeric,
ADD COLUMN IF NOT EXISTS fcf_per_share numeric,
ADD COLUMN IF NOT EXISTS operating_cash_flow_per_share numeric,
ADD COLUMN IF NOT EXISTS revenue_per_share numeric,
ADD COLUMN IF NOT EXISTS net_income_per_share numeric,
ADD COLUMN IF NOT EXISTS shareholders_equity_per_share numeric,
ADD COLUMN IF NOT EXISTS interest_debt_per_share numeric,
ADD COLUMN IF NOT EXISTS capex_per_share numeric,
ADD COLUMN IF NOT EXISTS capex_to_operating_cash_flow numeric,
ADD COLUMN IF NOT EXISTS capex_to_revenue numeric,
ADD COLUMN IF NOT EXISTS capex_to_depreciation numeric,
ADD COLUMN IF NOT EXISTS stock_based_compensation_to_revenue numeric,
ADD COLUMN IF NOT EXISTS earnings_yield numeric,
ADD COLUMN IF NOT EXISTS fcf_yield numeric,
ADD COLUMN IF NOT EXISTS debt_to_market_cap numeric,
ADD COLUMN IF NOT EXISTS payables_period numeric,
ADD COLUMN IF NOT EXISTS receivables_period numeric,
ADD COLUMN IF NOT EXISTS inventory_period numeric,
ADD COLUMN IF NOT EXISTS sales_general_and_administrative_to_revenue numeric,
ADD COLUMN IF NOT EXISTS research_and_development_to_revenue numeric,
ADD COLUMN IF NOT EXISTS intangibles_to_total_assets numeric,
ADD COLUMN IF NOT EXISTS dividend_paid_and_capex_coverage_ratio numeric,
ADD COLUMN IF NOT EXISTS price_fair_value numeric,
ADD COLUMN IF NOT EXISTS invested_capital_orig numeric,
ADD COLUMN IF NOT EXISTS invested_capital_usd numeric,
ADD COLUMN IF NOT EXISTS invested_capital_eur numeric;

-- Financial Ratios columns (from FMP Financial Ratios API)
ALTER TABLE financial_statements
ADD COLUMN IF NOT EXISTS current_ratio numeric,
ADD COLUMN IF NOT EXISTS quick_ratio numeric,
ADD COLUMN IF NOT EXISTS cash_ratio numeric,
ADD COLUMN IF NOT EXISTS debt_to_equity numeric,
ADD COLUMN IF NOT EXISTS debt_to_assets numeric,
ADD COLUMN IF NOT EXISTS interest_coverage numeric,
ADD COLUMN IF NOT EXISTS gross_profit_margin numeric,
ADD COLUMN IF NOT EXISTS operating_profit_margin numeric,
ADD COLUMN IF NOT EXISTS net_profit_margin numeric,
ADD COLUMN IF NOT EXISTS ebit_margin numeric,
ADD COLUMN IF NOT EXISTS ebitda_margin numeric,
ADD COLUMN IF NOT EXISTS pretax_profit_margin numeric,
ADD COLUMN IF NOT EXISTS asset_turnover numeric,
ADD COLUMN IF NOT EXISTS inventory_turnover numeric,
ADD COLUMN IF NOT EXISTS receivables_turnover numeric,
ADD COLUMN IF NOT EXISTS days_sales_outstanding numeric,
ADD COLUMN IF NOT EXISTS days_inventory_outstanding numeric,
ADD COLUMN IF NOT EXISTS days_payables_outstanding numeric,
ADD COLUMN IF NOT EXISTS cash_conversion_cycle numeric,
ADD COLUMN IF NOT EXISTS payout_ratio numeric,
ADD COLUMN IF NOT EXISTS dividend_per_share numeric,
ADD COLUMN IF NOT EXISTS effective_tax_rate numeric,
ADD COLUMN IF NOT EXISTS free_cash_flow_per_share_ratio numeric,
ADD COLUMN IF NOT EXISTS price_to_book_ratio numeric,
ADD COLUMN IF NOT EXISTS price_to_sales_ratio numeric,
ADD COLUMN IF NOT EXISTS price_earnings_ratio numeric,
ADD COLUMN IF NOT EXISTS price_to_free_cash_flows_ratio numeric,
ADD COLUMN IF NOT EXISTS price_to_operating_cash_flows_ratio numeric,
ADD COLUMN IF NOT EXISTS cash_per_share_ratio numeric,
ADD COLUMN IF NOT EXISTS operating_cash_flow_sales_ratio numeric,
ADD COLUMN IF NOT EXISTS free_cash_flow_operating_cash_flow_ratio numeric,
ADD COLUMN IF NOT EXISTS short_term_coverage_ratios numeric,
ADD COLUMN IF NOT EXISTS capital_expenditure_coverage_ratio numeric,
ADD COLUMN IF NOT EXISTS dividend_payments_coverage_ratio numeric,
ADD COLUMN IF NOT EXISTS price_earnings_to_growth_ratio numeric,
ADD COLUMN IF NOT EXISTS price_sales_ratio_ttm numeric,
ADD COLUMN IF NOT EXISTS ebit_per_revenue numeric,
ADD COLUMN IF NOT EXISTS operating_cycle numeric,
ADD COLUMN IF NOT EXISTS days_of_inventory_outstanding_ratio numeric,
ADD COLUMN IF NOT EXISTS days_of_payables_outstanding_ratio numeric,
ADD COLUMN IF NOT EXISTS days_of_sales_outstanding_ratio numeric,
ADD COLUMN IF NOT EXISTS fixed_asset_turnover numeric,
ADD COLUMN IF NOT EXISTS total_asset_turnover numeric,
ADD COLUMN IF NOT EXISTS company_equity_multiplier numeric,
ADD COLUMN IF NOT EXISTS cash_flow_to_debt_ratio numeric,
ADD COLUMN IF NOT EXISTS total_debt_to_capitalization numeric,
ADD COLUMN IF NOT EXISTS long_term_debt_to_capitalization numeric,
ADD COLUMN IF NOT EXISTS return_on_invested_capital numeric,
ADD COLUMN IF NOT EXISTS return_on_capital_employed numeric;

-- Raw data storage for Key Metrics and Ratios
ALTER TABLE financial_statements
ADD COLUMN IF NOT EXISTS raw_key_metrics jsonb,
ADD COLUMN IF NOT EXISTS raw_ratios jsonb;

-- Add comment to explain full_time_employees behavior
COMMENT ON COLUMN financial_statements.full_time_employees IS 'Always contains the latest company-wide employee count from the company profile, not historical quarterly values';
