// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://slpruxtkowlxawssqyup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNscHJ1eHRrb3dseGF3c3NxeXVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NTgwOTAsImV4cCI6MjA3MjAzNDA5MH0.mjB-ucA3FcQuwKiG1zs-6voNrvYHjpblKOSPijleHUQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});